import { OGGI, type DefVoce } from './tipi';

/** Persone: protagonisti, autori leggendari (senza periodo) e studiosi del campo. */
export const PERSONE: DefVoce[] = [
  // ——— Antichità ———
  {
    id: 'orfeo',
    titolo: 'Orfeo',
    tipo: 'persona',
    parte: 2,
    peso: 2,
    sommario:
      'Il cantore mitico a cui la tradizione attribuisce teogonie e testi rituali: figura leggendaria, non storica, la cui autorità fonda l’orfismo e gli garantisce un posto nella catena dei prisci theologi.',
    archi: [
      ['orfismo', 'attribuzione_infondata', 'I testi orfici sono opera di autori diversi lungo secoli: l’attribuzione al cantore mitico è il gesto fondativo della corrente, non un dato storico.'],
      ['morte-e-rinascita', 'usa_simbolo', 'La discesa agli inferi per Euridice: chi torna, torna incompleto'],
    ],
  },
  {
    id: 'pitagora',
    titolo: 'Pitagora',
    tipo: 'persona',
    parte: 2,
    peso: 3,
    periodo: [-570, -495],
    sommario:
      'Il fondatore della scuola di Crotone: numero, armonia, regola di vita, silenzio iniziatico. Della sua figura storica si sa pochissimo; della sua leggenda, moltissimo — ed è la leggenda ad aver agito nella storia.',
    archi: [['pitagorismo', 'influenza', 'La scuola e la sua leggenda']],
  },
  {
    id: 'platone',
    titolo: 'Platone',
    tipo: 'persona',
    parte: 2,
    peso: 4,
    periodo: [-428, -348],
    luoghi: ['atene'],
    sommario:
      'Non un esoterista, ma la sorgente involontaria di quasi tutto: il Timeo con il cosmo animato, l’anima del mondo, la scala dell’essere. Ogni platonismo successivo attingerà qui la propria metafisica.',
    archi: [
      ['neoplatonismo', 'influenza', 'La materia prima della sintesi plotiniana'],
      ['anima-mundi', 'elabora', 'Il Timeo: il cosmo come vivente dotato di anima'],
    ],
  },
  {
    id: 'apuleio',
    titolo: 'Apuleio',
    tipo: 'persona',
    parte: 2,
    peso: 2,
    periodo: [124, 170],
    sommario:
      'Retore, filosofo platonico, processato per magia: nel finale delle Metamorfosi lascia il più vivido resoconto antico di una conversione iniziatica, l’iniziazione di Lucio ai misteri di Iside.',
    archi: [['misteri-isiaci', 'elabora', 'Il libro XI delle Metamorfosi come testimonianza unica']],
  },
  {
    id: 'valentino',
    titolo: 'Valentino',
    tipo: 'persona',
    parte: 2,
    peso: 3,
    periodo: [100, 160],
    luoghi: ['alessandria', 'roma'],
    sommario:
      'Il maestro gnostico più influente: il suo sistema — pleroma, errore di Sofia, demiurgo, salvezza per gnosi — è il più elaborato e il più vicino al cristianesimo maggioritario, che per poco non lo elesse vescovo di Roma.',
    archi: [['gnosticismo', 'elabora', 'Il sistema valentiniano come forma più compiuta']],
    fonti: ['Filoramo, L’attesa della fine'],
  },
  {
    id: 'basilide',
    titolo: 'Basilide',
    tipo: 'persona',
    parte: 2,
    peso: 2,
    periodo: [100, 160],
    luoghi: ['alessandria'],
    sommario:
      'Maestro gnostico alessandrino, noto quasi solo dai confutatori: il suo sistema, con il dio ineffabile «che non è» e le 365 sfere celesti, è fra i più radicali della gnosi antica.',
    archi: [['gnosticismo', 'elabora']],
  },
  {
    id: 'ermete-trismegisto',
    titolo: 'Ermete Trismegisto',
    tipo: 'persona',
    parte: 2,
    peso: 5,
    alias: ['Hermes Trismegistus', 'Mercurius Trismegistus', 'Thoth'],
    sommario:
      'Figura sincretica che fonde il greco Ermes e l’egizio Thoth: autore leggendario del Corpus Hermeticum e patrono dell’intera tradizione ermetica. Non è mai esistito come persona storica — ed è stato creduto per millecinquecento anni.',
    archi: [
      ['corpus-hermeticum', 'attribuzione_infondata', 'L’attribuzione dei trattati a un sapiente egizio primordiale è pseudoepigrafia: i testi sono greci, di età imperiale, come dimostrato da Casaubon nel 1614.'],
      ['tavola-di-smeraldo', 'attribuzione_infondata', 'La Tavola compare in ambiente arabo fra VIII e IX secolo: l’attribuzione a Ermete è parte del suo dispositivo di autorità.'],
      ['pseudoepigrafia', 'elabora', 'Il caso più produttivo della storia del campo'],
    ],
    fonti: ['Copenhaver, Hermetica', 'Fowden, The Egyptian Hermes'],
  },
  {
    id: 'zosimo-di-panopoli',
    titolo: 'Zosimo di Panopoli',
    tipo: 'persona',
    parte: 2,
    peso: 3,
    periodo: [250, 320],
    luoghi: ['alessandria'],
    sommario:
      'La figura più significativa dell’alchimia greco-egizia: nei suoi scritti compaiono già le visioni in forma di sogno — il sacerdote smembrato e ricomposto — cioè il linguaggio della morte e rinascita applicato alla materia.',
    archi: [
      ['alchimia', 'elabora', 'Il primo autore alchemico di cui restino opere consistenti'],
      ['morte-e-rinascita', 'usa_simbolo', 'Le visioni del sacerdote smembrato'],
    ],
    fonti: ['Principe, The Secrets of Alchemy'],
  },
  {
    id: 'maria-l-ebrea',
    titolo: 'Maria l’Ebrea',
    tipo: 'persona',
    parte: 2,
    peso: 2,
    periodo: [200, 300],
    luoghi: ['alessandria'],
    alias: ['Maria Prophetissa', 'Maria la Giudea'],
    sommario:
      'Figura semileggendaria dell’alchimia alessandrina, a cui la tradizione attribuisce apparati di distillazione e il bagnomaria che ne conserva il nome: una delle prime autorità femminili del campo.',
    archi: [
      ['alchimia', 'elabora'],
      ['donne-ed-esoterismo', 'elabora', 'Autorità tecnica femminile in età tardoantica'],
    ],
  },
  {
    id: 'shimon-bar-yochai',
    titolo: 'Shimon bar Yochai',
    tipo: 'persona',
    parte: 2,
    peso: 2,
    periodo: [100, 170],
    alias: ['Rashbi'],
    sommario:
      'Il tannaita del II secolo a cui lo Zohar attribuisce se stesso: figura storica reale, ma la critica moderna — da Scholem in poi — riconosce nell’opera la mano castigliana duecentesca di Moses de León.',
    archi: [
      ['zohar', 'attribuzione_infondata', 'L’attribuzione dello Zohar al maestro del II secolo è pseudoepigrafia: lingua, fonti e contesto rimandano alla Castiglia degli anni Ottanta del Duecento (Scholem).'],
    ],
    fonti: ['Scholem, Le grandi correnti della mistica ebraica'],
  },
  {
    id: 'plotino',
    titolo: 'Plotino',
    tipo: 'persona',
    parte: 2,
    peso: 5,
    periodo: [204, 270],
    luoghi: ['alessandria', 'roma'],
    sommario:
      'Il filosofo dell’Uno: insegna pubblicamente a Roma, polemizza contro gli gnostici, e consegna all’Occidente — attraverso le Enneadi raccolte da Porfirio — la struttura emanativa che ogni esoterismo successivo presupporrà.',
    archi: [
      ['neoplatonismo', 'elabora', 'Il fondatore della scuola'],
      ['enneadi', 'elabora'],
      ['emanazione', 'elabora', 'Prohodos ed epistrophē: il doppio movimento'],
      ['gnosticismo', 'si_oppone_a', 'Il trattato contro gli gnostici: il cosmo non è una prigione'],
    ],
    fonti: ['Plotino, Enneadi'],
  },
  {
    id: 'porfirio',
    titolo: 'Porfirio',
    tipo: 'persona',
    parte: 2,
    peso: 2,
    periodo: [234, 305],
    sommario:
      'Discepolo ed editore di Plotino: ordina le Enneadi, scrive la Vita del maestro, e nella disputa con Giamblico difende la via puramente contemplativa contro la necessità del rito.',
    archi: [
      ['enneadi', 'elabora', 'L’edizione in sei gruppi di nove trattati'],
      ['teurgia', 'si_oppone_a', 'La contemplazione basta: la polemica a cui il De mysteriis risponde'],
    ],
  },
  {
    id: 'giamblico',
    titolo: 'Giamblico',
    tipo: 'persona',
    parte: 2,
    peso: 4,
    periodo: [245, 325],
    sommario:
      'Contro Porfirio sostiene che l’anima immersa nella materia non può risalire da sola: occorre la teurgia, il rito in cui sono gli dèi ad agire. Con questa mossa la pratica rituale entra a pieno titolo nella filosofia.',
    archi: [
      ['teurgia', 'elabora', 'Il De mysteriis come fondazione'],
      ['de-mysteriis', 'elabora'],
      ['neoplatonismo', 'elabora', 'La svolta rituale della scuola'],
    ],
    fonti: ['Giamblico, De mysteriis'],
  },
  {
    id: 'proclo',
    titolo: 'Proclo',
    tipo: 'persona',
    parte: 2,
    peso: 3,
    periodo: [412, 485],
    luoghi: ['atene'],
    sommario:
      'L’ultimo grande sistematico della scuola di Atene: gli Elementi di teologia trasmetteranno al Medioevo, spesso per vie indirette e sotto altri nomi, l’intera architettura emanativa.',
    archi: [
      ['neoplatonismo', 'elabora', 'La sistemazione scolastica dell’emanazione'],
      ['pseudo-dionigi', 'influenza', 'La fonte diretta del corpus dionisiano'],
    ],
  },
  {
    id: 'pseudo-dionigi',
    titolo: 'Pseudo-Dionigi Areopagita',
    tipo: 'persona',
    parte: 2,
    peso: 4,
    periodo: [470, 530],
    alias: ['Dionigi Areopagita', 'corpus dionysiacum'],
    sommario:
      'L’autore siriaco che si presenta come il discepolo ateniese di Paolo: il suo corpus trasferisce nella teologia cristiana le gerarchie angeliche e la teologia negativa neoplatoniche. La metafisica dell’esoterismo circola per un millennio come dottrina ortodossa.',
    archi: [
      ['neoplatonismo', 'deriva_da', 'Proclo cristianizzato'],
      ['pseudoepigrafia', 'elabora', 'Lo pseudonimo apostolico come dispositivo di autorità'],
      ['luce-e-tenebra', 'usa_simbolo', 'La caligine luminosa della teologia negativa'],
    ],
  },

  // ——— Medioevo ———
  {
    id: 'ildegarda-di-bingen',
    titolo: 'Ildegarda di Bingen',
    tipo: 'persona',
    parte: 2,
    peso: 3,
    periodo: [1098, 1179],
    sommario:
      'Visionaria, medica e compositrice: la viriditas, la verdeggianza che percorre creato e persona, formula pienamente la corrispondenza uomo-cosmo. Tutto pubblico e approvato: il caso che mostra quanto il confine dipenda dalla posizione, non dal contenuto.',
    archi: [
      ['macrocosmo-microcosmo', 'elabora', 'La corrispondenza formulata in ambito monastico ortodosso'],
      ['donne-ed-esoterismo', 'elabora', 'Autorità visionaria femminile nel XII secolo'],
    ],
  },
  {
    id: 'gioacchino-da-fiore',
    titolo: 'Gioacchino da Fiore',
    tipo: 'persona',
    parte: 2,
    peso: 3,
    periodo: [1135, 1202],
    sommario:
      'La dottrina delle tre età — del Padre, del Figlio, dello Spirito — introduce uno schema di storia sacra a periodi che riemergerà, secolarizzato, in ogni successiva attesa di un’era nuova, fino al New Age.',
    archi: [
      ['tempo-ciclico', 'elabora', 'Le età del mondo come schema di attesa'],
      ['new-age', 'influenza', 'L’attesa dell’età dello Spirito, secolarizzata'],
    ],
  },
  {
    id: 'abulafia',
    titolo: 'Abraham Abulafia',
    tipo: 'persona',
    parte: 2,
    peso: 3,
    periodo: [1240, 1291],
    alias: ['Abraham Abulafia'],
    sommario:
      'La cabala estatica o profetica: non speculazione sulle sefirot ma tecnica — permutazione di lettere, respirazione, recitazione dei nomi — per raggiungere uno stato di unione. Il ramo più esplicitamente operativo della mistica ebraica.',
    archi: [
      ['cabala', 'elabora', 'La linea estatica accanto a quella teosofico-speculativa'],
      ['vie-contemplative', 'pratica', 'Le tecniche di permutazione e recitazione'],
    ],
    fonti: ['Idel, Cabbalà. Nuove prospettive', 'Scholem, Le grandi correnti della mistica ebraica'],
  },

  {
    id: 'jabir-ibn-hayyan',
    titolo: 'Jabir ibn Hayyan',
    tipo: 'persona',
    parte: 2,
    peso: 2,
    periodo: [721, 815],
    alias: ['Geber'],
    sommario:
      'Il nome a cui è attribuito il grande corpus alchemico arabo — in larga parte opera di autori successivi — che elabora la teoria zolfo-mercurio: se i metalli differiscono di grado e non di natura, la trasmutazione è concepibile.',
    archi: [
      ['alchimia', 'elabora', 'La teoria zolfo-mercurio della fase araba'],
      ['pseudoepigrafia', 'elabora', 'Il corpus jabiriano e poi lo pseudo-Geber latino: attribuzioni stratificate'],
    ],
    fonti: ['Principe, The Secrets of Alchemy'],
  },

  // ——— Rinascimento ———
  {
    id: 'ficino',
    titolo: 'Marsilio Ficino',
    tipo: 'persona',
    parte: 2,
    peso: 5,
    periodo: [1433, 1499],
    luoghi: ['firenze'],
    alias: ['Marsilio Ficino', 'Ficinus'],
    sommario:
      'Traduttore del Corpus Hermeticum e di Platone, teorico della magia astrale medica: la figura che nel 1463 riapre all’Occidente la sapienza ermetica, credendola antichissima.',
    archi: [
      ['corpus-hermeticum', 'elabora', 'Traduzione del 1463, stampata nel 1471 come Pimander'],
      ['de-vita', 'elabora'],
      ['prisca-theologia', 'elabora', 'Fonda la catena dei prisci theologi sull’errore di datazione'],
      ['neoplatonismo', 'deriva_da', 'Platonico cristiano: traduce Platone e Plotino'],
      ['picatrix', 'deriva_da', 'Fonte diretta del De vita III'],
      ['talismani', 'pratica', 'La magia astrale medica del De vita coelitus comparanda'],
      ['esoterismo-e-musica', 'elabora', 'Gli inni orfici cantati alla lira: la prima terapia musicale moderna'],
      ['magia-rinascimentale', 'elabora'],
    ],
    fonti: ['Yates, Giordano Bruno e la tradizione ermetica', 'Walker, Spiritual and Demonic Magic'],
  },
  {
    id: 'pico-della-mirandola',
    titolo: 'Giovanni Pico della Mirandola',
    tipo: 'persona',
    parte: 2,
    peso: 4,
    periodo: [1463, 1494],
    luoghi: ['firenze', 'roma'],
    alias: ['Pico'],
    sommario:
      'A ventitré anni pubblica novecento tesi e l’Oratio: l’uomo camaleonte, senza natura fissa, capace di degradarsi o ascendere. Con lui la cabala entra nella cultura cristiana come strumento apologetico e magico.',
    archi: [
      ['oratio-de-hominis-dignitate', 'elabora'],
      ['cabala-cristiana', 'elabora', 'Le tesi cabalistiche del 1486 ne sono l’atto di nascita'],
      ['magia-rinascimentale', 'elabora'],
      ['ficino', 'deriva_da', 'L’ambiente del platonismo fiorentino'],
    ],
    fonti: ['Yates, Giordano Bruno e la tradizione ermetica'],
  },
  {
    id: 'agrippa',
    titolo: 'Cornelio Agrippa',
    tipo: 'persona',
    parte: 2,
    peso: 5,
    periodo: [1486, 1535],
    alias: ['Heinrich Cornelius Agrippa', 'Agrippa di Nettesheim'],
    sommario:
      'L’autore del manuale che l’Europa leggerà per tre secoli: il De occulta philosophia, con la struttura in tre mondi — elementare, celeste, intellettuale — che resterà lo schema della magia occidentale fino alla Golden Dawn.',
    archi: [
      ['de-occulta-philosophia', 'elabora'],
      ['magia-rinascimentale', 'elabora'],
      ['cabala-cristiana', 'deriva_da', 'La integra nella sintesi dei tre mondi'],
      ['magia-cerimoniale', 'pratica', 'Il terzo libro: nomi divini, angeli, purificazione dell’operatore'],
    ],
    fonti: ['Yates, Giordano Bruno e la tradizione ermetica'],
  },
  {
    id: 'paracelso',
    titolo: 'Paracelso',
    tipo: 'persona',
    parte: 2,
    peso: 4,
    periodo: [1493, 1541],
    alias: ['Theophrastus Bombastus von Hohenheim'],
    sommario:
      'Il medico ribelle che cambia l’obiettivo dell’alchimia: non fare oro ma fare medicine. I tria prima, la dottrina delle segnature, la distinzione fra imaginatio e phantasia: da qui iatrochimica e spagiria.',
    archi: [
      ['paracelsismo', 'elabora'],
      ['segnature', 'elabora'],
      ['alchimia', 'elabora', 'La svolta medica dell’arte'],
      ['immaginazione', 'elabora', 'Imaginatio come facoltà reale contro la phantasia'],
    ],
    fonti: ['Principe, The Secrets of Alchemy'],
  },
  {
    id: 'giordano-bruno',
    titolo: 'Giordano Bruno',
    tipo: 'persona',
    parte: 2,
    peso: 4,
    periodo: [1548, 1600],
    luoghi: ['roma', 'londra'],
    sommario:
      'Porta l’arte della memoria a un uso magico: le immagini mnemoniche organizzano l’anima secondo la struttura del cosmo. Il rogo del 1600 ne farà, impropriamente, un martire della scienza; fu un martire della libertà di pensiero.',
    archi: [
      ['arte-della-memoria', 'elabora', 'Da tecnica retorica a strumento di riforma interiore'],
      ['magia-rinascimentale', 'elabora'],
      ['ermetismo', 'deriva_da', 'La religione egizia del Sole come orizzonte'],
      ['rogo-di-giordano-bruno', 'elabora'],
    ],
    fonti: ['Yates, Giordano Bruno e la tradizione ermetica', 'Yates, L’arte della memoria'],
  },
  {
    id: 'john-dee',
    titolo: 'John Dee',
    tipo: 'persona',
    parte: 2,
    peso: 4,
    periodo: [1527, 1608],
    luoghi: ['londra'],
    sommario:
      'Matematico, consigliere di Elisabetta I, fra gli uomini più dotti d’Inghilterra: dal 1582, con il medium Edward Kelley, riceve il sistema di comunicazione angelica — tavole, alfabeto, lingua — che chiamiamo enochiano.',
    archi: [
      ['magia-rinascimentale', 'elabora'],
      ['golden-dawn', 'influenza', 'Il sistema enochiano riscoperto e riusato tre secoli dopo'],
      ['magia-cerimoniale', 'pratica', 'Le azioni angeliche con Kelley'],
    ],
    fonti: ['Yates, Giordano Bruno e la tradizione ermetica'],
  },
  {
    id: 'isaac-luria',
    titolo: 'Isaac Luria',
    tipo: 'persona',
    parte: 2,
    peso: 4,
    periodo: [1534, 1572],
    luoghi: ['safed'],
    alias: ['Ari', 'Arizal'],
    sommario:
      'Il rifondatore della cabala a Safed: tzimtzum, rottura dei vasi, tikkun. Morto a trentotto anni senza quasi scrivere, il suo insegnamento orale — trasmesso dai discepoli — diventa la cosmogonia più influente dell’ebraismo moderno.',
    archi: [
      ['cabala-luriana', 'elabora'],
      ['emanazione', 'elabora', 'La contrazione divina che precede ogni emanazione'],
      ['reintegrazione', 'elabora', 'Il tikkun come compito umano'],
    ],
    fonti: ['Scholem, Le grandi correnti della mistica ebraica'],
  },

  // ——— Età moderna ———
  {
    id: 'christian-rosenkreutz',
    titolo: 'Christian Rosenkreutz',
    tipo: 'persona',
    parte: 2,
    peso: 2,
    alias: ['C.R.C.', 'Rosenkreuz'],
    sommario:
      'Il fondatore leggendario della fraternità rosacrociana, il viaggiatore in Oriente la cui tomba sarebbe stata ritrovata intatta dopo centoventi anni: un personaggio letterario dei manifesti, mai esistito.',
    archi: [
      ['rosacrocianesimo', 'attribuzione_infondata', 'Il fondatore è un personaggio del racconto dei manifesti (Andreae parlerà di ludibrium): nessuna attestazione indipendente della sua esistenza o della fraternità originaria.'],
      ['fama-fraternitatis', 'elabora', 'Il protagonista del mito di fondazione'],
    ],
    fonti: ['Yates, L’illuminismo dei Rosacroce'],
  },
  {
    id: 'jacob-boehme',
    titolo: 'Jacob Böhme',
    tipo: 'persona',
    parte: 2,
    peso: 4,
    periodo: [1575, 1624],
    alias: ['Jakob Böhme', 'Boehme'],
    sommario:
      'Il calzolaio di Görlitz che dopo un’esperienza visionaria affronta il problema dell’origine del male in Dio stesso: l’Ungrund, il fondo senza fondo, e la divinità come processo attraversato da tensione tragica.',
    archi: [
      ['teosofia-cristiana', 'elabora', 'Il capostipite della corrente'],
      ['paracelsismo', 'deriva_da', 'Il lessico alchemico-paracelsiano delle sue opere'],
      ['esoterismo-e-letteratura', 'influenza', 'Schelling e Hegel lo leggono; il romanticismo lo assorbe'],
    ],
    fonti: ['Faivre, Accès de l’ésotérisme occidental'],
  },
  {
    id: 'swedenborg',
    titolo: 'Emanuel Swedenborg',
    tipo: 'persona',
    parte: 2,
    peso: 4,
    periodo: [1688, 1772],
    luoghi: ['londra'],
    sommario:
      'Scienziato di primo piano che dopo il 1745 dichiara accesso costante al mondo spirituale: la sua dottrina delle corrispondenze — ogni realtà naturale come corrispettivo di una spirituale — avrà un impatto letterario enorme, da Blake ai simbolisti.',
    archi: [
      ['corrispondenze', 'elabora', 'La versione moderna e sistematica della dottrina'],
      ['teosofia-cristiana', 'elabora'],
      ['esoterismo-e-letteratura', 'influenza', 'Blake, Balzac, Baudelaire e il simbolismo'],
      ['spiritismo', 'influenza', 'I resoconti del mondo degli spiriti preparano il terreno'],
    ],
    fonti: ['Godwin, The Theosophical Enlightenment'],
  },
  {
    id: 'newton',
    titolo: 'Isaac Newton',
    tipo: 'persona',
    parte: 2,
    peso: 3,
    periodo: [1642, 1727],
    luoghi: ['londra'],
    sommario:
      'Il fondatore della fisica classica dedicò all’alchimia decine di migliaia di pagine manoscritte, ritenendo di fare scienza sperimentale: il caso che dimostra come la separazione fra chimica e alchimia sia un evento storico, non un dato di natura.',
    archi: [
      ['alchimia', 'pratica', 'Il laboratorio di Cambridge e i manoscritti alchemici'],
      ['esoterismo-e-scienza', 'elabora', 'Il caso esemplare del confine non ancora tracciato'],
    ],
    fonti: ['Principe, The Secrets of Alchemy'],
  },
  {
    id: 'martinez-de-pasqually',
    titolo: 'Martinez de Pasqually',
    tipo: 'persona',
    parte: 2,
    peso: 3,
    periodo: [1727, 1774],
    sommario:
      'Il fondatore degli Élus Coëns, l’ordine dedito a un’intensa pratica teurgica finalizzata alla reintegrazione dell’uomo nel suo stato primordiale: la matrice cerimoniale da cui uscirà, per superamento, il martinismo.',
    archi: [
      ['martinismo', 'elabora', 'L’ordine originario della corrente'],
      ['teurgia', 'pratica', 'Le operazioni degli Élus Coëns'],
      ['reintegrazione', 'elabora'],
    ],
  },
  {
    id: 'saint-martin',
    titolo: 'Louis-Claude de Saint-Martin',
    tipo: 'persona',
    parte: 2,
    peso: 3,
    periodo: [1743, 1803],
    luoghi: ['parigi'],
    alias: ['il Filosofo Incognito'],
    sommario:
      'Discepolo di Pasqually, abbandona il cerimoniale per una via interiore — la «via del cuore» — e traduce Böhme: da lui prende nome il martinismo, nelle sue diverse e posteriori organizzazioni.',
    archi: [
      ['martinismo', 'elabora', 'La svolta interiore della corrente'],
      ['jacob-boehme', 'deriva_da', 'Il traduttore francese del teosofo di Görlitz'],
    ],
  },
  {
    id: 'mesmer',
    titolo: 'Franz Anton Mesmer',
    tipo: 'persona',
    parte: 2,
    peso: 3,
    periodo: [1734, 1815],
    luoghi: ['parigi'],
    sommario:
      'Il medico del fluido universale: la commissione reale del 1784 stabilì che gli effetti erano reali ma dovuti all’immaginazione — individuando, senza saperlo, la suggestione. Dalla sua eredità: l’ipnosi e, per altra via, l’inconscio.',
    archi: [
      ['mesmerismo', 'elabora'],
      ['commissione-sul-mesmerismo', 'elabora'],
    ],
    fonti: ['Godwin, The Theosophical Enlightenment'],
  },
  {
    id: 'eliphas-levi',
    titolo: 'Éliphas Lévi',
    tipo: 'persona',
    parte: 2,
    peso: 5,
    periodo: [1810, 1875],
    luoghi: ['parigi'],
    alias: ['Alphonse-Louis Constant'],
    sommario:
      'Il fondatore dell’occultismo moderno: nel Dogme et rituel unifica magia cerimoniale, cabala, alchimia e tarocchi, stabilendo la corrispondenza arcani-lettere ebraiche. Senza fondamento storico, con fortuna immensa.',
    archi: [
      ['occultismo', 'elabora', 'L’atto di fondazione della corrente'],
      ['dogme-et-rituel', 'elabora'],
      ['tarocchi', 'elabora', 'La saldatura con la cabala che quasi nessuno percepisce più come invenzione'],
      ['esoterismo', 'elabora', 'Diffonde il sostantivo «ésotérisme» a metà Ottocento'],
    ],
    fonti: ['Godwin, The Theosophical Enlightenment'],
  },
  {
    id: 'blavatsky',
    titolo: 'Helena Petrovna Blavatsky',
    tipo: 'persona',
    parte: 2,
    peso: 5,
    periodo: [1831, 1891],
    luoghi: ['new-york', 'londra'],
    alias: ['HPB', 'Madame Blavatsky'],
    sommario:
      'La fondatrice della Società Teosofica: con La dottrina segreta costruisce una sintesi di dimensioni cosmiche e porta karma, reincarnazione e chakra nel lessico occidentale. Sulle razze-radici, il volume dice ciò che va detto: materiale in sé indifendibile.',
    archi: [
      ['teosofia', 'elabora'],
      ['dottrina-segreta', 'elabora'],
      ['donne-ed-esoterismo', 'elabora', 'Alla testa di un’organizzazione internazionale nel XIX secolo'],
    ],
    fonti: ['Godwin, The Theosophical Enlightenment'],
  },
  {
    id: 'steiner',
    titolo: 'Rudolf Steiner',
    tipo: 'persona',
    parte: 2,
    peso: 4,
    periodo: [1861, 1925],
    sommario:
      'Dalla sezione tedesca della Società Teosofica all’Antroposofia: una «scienza dello spirito» con applicazioni durature — la scuola Waldorf (1919), l’agricoltura biodinamica, la medicina antroposofica.',
    archi: [
      ['antroposofia', 'elabora'],
      ['teosofia', 'deriva_da', 'Il distacco del 1912-13'],
    ],
  },
  {
    id: 'crowley',
    titolo: 'Aleister Crowley',
    tipo: 'persona',
    parte: 2,
    peso: 5,
    periodo: [1875, 1947],
    luoghi: ['londra', 'il-cairo'],
    alias: ['la Grande Bestia', 'Frater Perdurabo'],
    sommario:
      'Il fondatore di Thelema: tecnico rigoroso che introduce elementi yogici e un’esigenza di verifica sperimentale, e figura autodistruttiva la cui vita ha danneggiato la ricezione dell’opera. Il precetto della Volontà vera è sistematicamente frainteso.',
    archi: [
      ['thelema', 'elabora'],
      ['liber-al', 'elabora'],
      ['golden-dawn', 'deriva_da', 'Iniziato nel 1898, ne porta con sé il sistema'],
      ['magia-cerimoniale', 'pratica'],
    ],
    fonti: ['Owen, The Place of Enchantment'],
  },
  {
    id: 'gurdjieff',
    titolo: 'George Ivanovič Gurdjieff',
    tipo: 'persona',
    parte: 2,
    peso: 3,
    periodo: [1866, 1949],
    luoghi: ['parigi'],
    sommario:
      'Il maestro della Quarta Via: l’uomo ordinario vive nel sonno, e la sveglia richiede lavoro su di sé in condizioni deliberatamente scomode. Ouspensky ne darà l’esposizione più chiara.',
    archi: [
      ['quarta-via', 'elabora'],
      ['vie-contemplative', 'pratica', 'Il ricordo di sé'],
    ],
  },
  {
    id: 'gardner',
    titolo: 'Gerald Gardner',
    tipo: 'persona',
    parte: 2,
    peso: 3,
    periodo: [1884, 1964],
    luoghi: ['londra'],
    sommario:
      'Nel 1954, abrogate le leggi inglesi contro la stregoneria, presenta la Wicca come sopravvivenza di un culto antico: la ricerca ha mostrato che l’aveva composta lui, con materiali della Golden Dawn, di Crowley e della tesi infondata di Murray.',
    archi: [
      ['wicca', 'elabora', 'Il compositore della stregoneria moderna'],
      ['invenzione-di-tradizione', 'elabora'],
    ],
    fonti: ['Hutton, The Triumph of the Moon'],
  },
  {
    id: 'starhawk',
    titolo: 'Starhawk',
    tipo: 'persona',
    parte: 2,
    peso: 2,
    periodo: [1951, OGGI],
    sommario:
      'Con La danza a spirale (1979) salda stregoneria, femminismo ed ecologia: la teologia della Dea come progetto politico-religioso, l’esito più culturalmente rilevante del neopaganesimo.',
    archi: [
      ['wicca', 'elabora', 'La corrente femminista della stregoneria'],
      ['donne-ed-esoterismo', 'elabora'],
    ],
    fonti: ['Hutton, The Triumph of the Moon'],
  },
  {
    id: 'guenon',
    titolo: 'René Guénon',
    tipo: 'persona',
    parte: 2,
    peso: 4,
    periodo: [1886, 1951],
    luoghi: ['parigi', 'il-cairo'],
    sommario:
      'Rompe con l’occultismo e costruisce l’opera opposta: Tradizione primordiale, ortodossia delle forme, affiliazione regolare, modernità come regno della quantità. Muore al Cairo come musulmano in ambiente sufi.',
    archi: [
      ['tradizionalismo', 'elabora', 'Il fondatore della corrente'],
      ['occultismo', 'si_oppone_a', 'La rottura con l’ambiente di provenienza'],
      ['sufismo', 'pratica', 'L’affiliazione alla via di Abd al-Rahman Illaysh'],
      ['catena-iniziatica', 'elabora', 'Il criterio della regolarità'],
    ],
    fonti: ['Sedgwick, Against the Modern World'],
  },
  {
    id: 'evola',
    titolo: 'Julius Evola',
    tipo: 'persona',
    parte: 2,
    peso: 3,
    periodo: [1898, 1974],
    luoghi: ['roma'],
    sommario:
      'Declina il tradizionalismo in senso guerriero e politico, con adesioni e simpatie che ne fanno una figura compromessa e ancora oggetto di uso militante: da studiare con la doppia lente — come dottrina e come fenomeno storico.',
    archi: [
      ['tradizionalismo', 'elabora', 'La versione «guerriera» della corrente'],
      ['esoterismo-e-politica', 'elabora', 'Il caso italiano dell’uso politico del materiale tradizionale'],
    ],
    fonti: ['Sedgwick, Against the Modern World'],
  },

  // ——— Studiosi (Parte I) e ricezioni (Parte VI) ———
  {
    id: 'jung',
    titolo: 'Carl Gustav Jung',
    tipo: 'persona',
    parte: 6,
    peso: 5,
    periodo: [1875, 1961],
    luoghi: ['ascona'],
    sommario:
      'Il mediatore principale fra esoterismo e cultura contemporanea: inconscio collettivo, archetipi, individuazione, sincronicità, e la rilettura dell’alchimia come processo psichico. Operazione potentissima — e da situare storicamente.',
    archi: [
      ['inconscio-collettivo', 'elabora'],
      ['archetipi', 'elabora'],
      ['individuazione', 'elabora'],
      ['sincronicita', 'elabora'],
      ['psicologia-e-alchimia', 'elabora'],
      ['alchimia', 'rilegge', 'La lettura psicologica: nuova opera, non decifrazione della vecchia'],
      ['convegni-di-eranos', 'elabora', 'Figura centrale del circolo di Ascona'],
    ],
    fonti: ['Jung, Psicologia e alchimia', 'Shamdasani, Jung and the Making of Modern Psychology'],
  },
  {
    id: 'yeats',
    titolo: 'W.B. Yeats',
    tipo: 'persona',
    parte: 6,
    peso: 3,
    periodo: [1865, 1939],
    luoghi: ['londra'],
    sommario:
      'Premio Nobel e membro attivo della Golden Dawn per decenni: il caso maggiore di letteratura come fonte — l’opera tarda poggia su un sistema visionario esposto in A Vision.',
    archi: [
      ['golden-dawn', 'elabora', 'Membro attivo con il nome di Daemon est Deus Inversus'],
      ['esoterismo-e-letteratura', 'elabora'],
    ],
    fonti: ['Owen, The Place of Enchantment'],
  },
  {
    id: 'hilma-af-klint',
    titolo: 'Hilma af Klint',
    tipo: 'persona',
    parte: 6,
    peso: 3,
    periodo: [1862, 1944],
    sommario:
      'Dipinge dal 1906 opere astratte di grandi dimensioni su indicazioni ricevute in seduta medianica, e ne dispone la non esposizione per decenni: la pioniera dell’astrazione che il canone ha riconosciuto con un secolo di ritardo.',
    archi: [
      ['esoterismo-e-arte', 'elabora', 'Il caso più radicale di astrazione a matrice medianica'],
      ['teosofia', 'deriva_da', 'L’ambiente teosofico-spiritista svedese'],
      ['donne-ed-esoterismo', 'elabora'],
    ],
  },
  {
    id: 'scholem',
    titolo: 'Gershom Scholem',
    tipo: 'persona',
    parte: 1,
    peso: 4,
    periodo: [1897, 1982],
    luoghi: ['ascona'],
    sommario:
      'Il fondatore dello studio scientifico della cabala contro secoli di disprezzo accademico: la filologia al servizio della mistica, l’attribuzione dello Zohar a Moses de León, la storia delle correnti messianiche.',
    archi: [
      ['cabala', 'rilegge', 'La fondazione dello studio storico-critico'],
      ['zohar', 'elabora', 'La dimostrazione dell’autore castigliano'],
      ['convegni-di-eranos', 'elabora'],
      ['religionismo', 'elabora'],
    ],
    fonti: ['Scholem, Le grandi correnti della mistica ebraica'],
  },
  {
    id: 'corbin',
    titolo: 'Henry Corbin',
    tipo: 'persona',
    parte: 1,
    peso: 3,
    periodo: [1903, 1978],
    luoghi: ['ascona', 'parigi'],
    sommario:
      'Restituisce all’Occidente l’esoterismo islamico e conia «mundus imaginalis»: il livello intermedio di realtà con leggi proprie. Religionista esemplare: miniera di intuizioni, metodo da maneggiare con cautela.',
    archi: [
      ['mundus-imaginalis', 'elabora'],
      ['sufismo', 'rilegge', 'L’interprete di Ibn Arabi e della filosofia iranica'],
      ['convegni-di-eranos', 'elabora'],
      ['religionismo', 'elabora'],
    ],
    fonti: ['Corbin, L’immaginazione creatrice'],
  },
  {
    id: 'eliade',
    titolo: 'Mircea Eliade',
    tipo: 'persona',
    parte: 1,
    peso: 3,
    periodo: [1907, 1986],
    luoghi: ['ascona'],
    sommario:
      'Il costruttore del lessico comparativo ancora in uso — sacro e profano, illud tempus, iniziazione come cosmogonia ripetuta. Il caso più discusso di religionismo: simpatie ideologiche giovanili che ne condizionano l’impianto.',
    archi: [
      ['iniziazione', 'rilegge', 'L’iniziazione ripete la cosmogonia'],
      ['alchimia', 'rilegge', 'Arti del metallo e alchimia: il fabbro e l’alchimista come acceleratori del tempo'],
      ['convegni-di-eranos', 'elabora'],
      ['religionismo', 'elabora'],
    ],
    fonti: ['Eliade, Arti del metallo e alchimia'],
  },
  {
    id: 'yates',
    titolo: 'Frances Yates',
    tipo: 'persona',
    parte: 1,
    peso: 4,
    periodo: [1899, 1981],
    luoghi: ['londra'],
    sommario:
      'La storica che riscrisse la mappa del Rinascimento: Giordano Bruno e la tradizione ermetica (1964) impone la «tradizione ermetica» come categoria storiografica; L’illuminismo dei Rosacroce ricostruisce il contesto dei manifesti.',
    archi: [
      ['ermetismo', 'rilegge', 'La tesi Yates: l’ermetismo come motore del Rinascimento'],
      ['rosacrocianesimo', 'rilegge', 'Il contesto palatino dei manifesti'],
      ['arte-della-memoria', 'rilegge'],
      ['donne-ed-esoterismo', 'elabora'],
    ],
    fonti: ['Yates, Giordano Bruno e la tradizione ermetica', 'Yates, L’illuminismo dei Rosacroce'],
  },
  {
    id: 'faivre',
    titolo: 'Antoine Faivre',
    tipo: 'persona',
    parte: 1,
    peso: 4,
    periodo: [1934, 2021],
    luoghi: ['parigi'],
    sommario:
      'Il titolare della prima cattedra dedicata (EPHE, 1979) e l’autore della definizione tipologica: le quattro caratteristiche — corrispondenze, natura vivente, immaginazione e mediazioni, trasmutazione — che hanno reso studiabile il campo.',
    archi: [
      ['esoterismo', 'elabora', 'La definizione per aria di famiglia'],
      ['corrispondenze', 'elabora'],
      ['studio-accademico', 'elabora', 'La cattedra del 1979 come atto di nascita disciplinare'],
    ],
    fonti: ['Faivre, Accès de l’ésotérisme occidental'],
  },
  {
    id: 'hanegraaff',
    titolo: 'Wouter Hanegraaff',
    tipo: 'persona',
    parte: 1,
    peso: 3,
    periodo: [1961, OGGI],
    sommario:
      'Allievo e critico di Faivre, direttore del centro di Amsterdam: Esotericism and the Academy (2012) sposta il baricentro — l’esoterismo come «sapere rifiutato», posizione nel campo del sapere più che contenuto.',
    archi: [
      ['sapere-rifiutato', 'elabora'],
      ['studio-accademico', 'elabora'],
      ['alchimia-e-psicologia', 'si_oppone_a', 'La critica storiografica alla lettura junghiana'],
    ],
    fonti: ['Hanegraaff, Esotericism and the Academy'],
  },
  {
    id: 'von-stuckrad',
    titolo: 'Kocku von Stuckrad',
    tipo: 'persona',
    parte: 1,
    peso: 2,
    periodo: [1966, OGGI],
    sommario:
      'La terza via definitoria: l’esoterismo come elemento strutturale del discorso religioso occidentale — la rivendicazione di un sapere superiore e la dialettica di occultamento e rivelazione che la accompagna.',
    archi: [['discorso-del-sapere-superiore', 'elabora']],
    fonti: ['von Stuckrad, Western Esotericism'],
  },
  {
    id: 'van-gennep',
    titolo: 'Arnold van Gennep',
    tipo: 'persona',
    parte: 4,
    peso: 2,
    periodo: [1873, 1957],
    sommario:
      'L’etnografo dei riti di passaggio: lo schema tripartito — separazione, margine, aggregazione — che Victor Turner approfondirà con la nozione di liminalità, e che rende leggibile ogni iniziazione.',
    archi: [['iniziazione', 'rilegge', 'Lo schema dei riti di passaggio']],
    fonti: ['van Gennep, I riti di passaggio', 'Turner, Il processo rituale'],
  },
];
