import { OGGI, type DefVoce } from './tipi';

/** Le correnti storiche (asse cronologico della Parte II, più le tre non occidentali della nota comparativa). */
export const CORRENTI: DefVoce[] = [
  {
    id: 'misteri-eleusini',
    titolo: 'Misteri eleusini',
    tipo: 'corrente',
    parte: 2,
    peso: 4,
    periodo: [-1450, 392],
    luoghi: ['atene'],
    alias: ['Eleusi', 'misteri di Eleusi'],
    sommario:
      'Il più celebre culto misterico greco: iniziazione individuale e volontaria, un segreto mantenuto per un millennio, la matrice rituale — cose dette, compiute, mostrate — di quasi tutta l’iniziazione occidentale.',
    archi: [
      ['iniziazione', 'pratica', 'La struttura legómena/drómena/deiknýmena è la matrice della ritualità iniziatica'],
      ['morte-e-rinascita', 'usa_simbolo', 'Il mito di Persefone: discesa e ritorno stagionale'],
      ['statuto-del-segreto', 'elabora', 'Caso esemplare di segreto rituale: coperta è la scena, non la notizia'],
      ['massoneria', 'attribuzione_infondata', 'La continuità fra i misteri antichi e la massoneria, rivendicata dagli alti gradi settecenteschi, non ha alcuna base documentaria: fra la chiusura di Eleusi e il 1717 corrono tredici secoli senza catena.'],
    ],
    fonti: ['Burkert, Antichi culti misterici'],
  },
  {
    id: 'misteri-isiaci',
    titolo: 'Misteri di Iside',
    tipo: 'corrente',
    parte: 2,
    peso: 2,
    periodo: [-300, 400],
    luoghi: ['alessandria', 'roma'],
    alias: ['culti isiaci', 'Iside e Osiride'],
    sommario:
      'I culti ellenistici di Iside e Osiride, diffusi in tutto il Mediterraneo: Apuleio ne lascia nelle Metamorfosi il più vivido resoconto antico di una conversione iniziatica.',
    archi: [
      ['misteri-eleusini', 'contemporaneo_di'],
      ['morte-e-rinascita', 'usa_simbolo', 'Osiride smembrato e ricomposto'],
    ],
    fonti: ['Burkert, Antichi culti misterici', 'Apuleio, Metamorfosi'],
  },
  {
    id: 'mitraismo',
    titolo: 'Mitraismo',
    tipo: 'corrente',
    parte: 2,
    peso: 3,
    periodo: [50, 400],
    luoghi: ['roma'],
    alias: ['misteri di Mitra'],
    sommario:
      'Il culto misterico diffuso nell’esercito romano: sette gradi corrispondenti a sette pianeti, celebrati in ambienti sotterranei che rappresentano la volta celeste. La gradualità iniziatica in forma pura.',
    archi: [
      ['sistema-dei-gradi', 'pratica', 'Sette gradi, sette pianeti: ogni soglia corrisponde a un livello cosmico'],
      ['ponte-e-scala', 'usa_simbolo', 'La scala planetaria a sette gradini'],
      ['misteri-eleusini', 'contemporaneo_di'],
    ],
    fonti: ['Burkert, Antichi culti misterici'],
  },
  {
    id: 'orfismo',
    titolo: 'Orfismo',
    tipo: 'corrente',
    parte: 2,
    peso: 3,
    periodo: [-600, 400],
    alias: ['orfici'],
    sommario:
      'Movimento diffuso senza chiesa né clero, riconoscibile dai testi attribuiti a Orfeo e dalle pratiche di purificazione: l’anima divina imprigionata nel corpo (sōma/sēma) e il viaggio ultraterreno con formule di riconoscimento.',
    archi: [
      ['misteri-eleusini', 'contemporaneo_di'],
      ['pitagorismo', 'influenza', 'Dottrine e pratiche orfico-pitagoriche strettamente intrecciate'],
      ['morte-e-rinascita', 'usa_simbolo', 'Il ciclo delle vite e la purificazione'],
      ['specchio', 'usa_simbolo', 'Lo specchio con cui i Titani distraggono Dioniso'],
    ],
    fonti: ['Burkert, Antichi culti misterici'],
  },
  {
    id: 'pitagorismo',
    titolo: 'Pitagorismo',
    tipo: 'corrente',
    parte: 2,
    peso: 4,
    periodo: [-530, 300],
    alias: ['scuola pitagorica'],
    sommario:
      'La prima organizzazione occidentale che unisce ricerca intellettuale, regola di vita e struttura iniziatica: il numero come struttura del reale, l’armonia come sua manifestazione udibile, le tecniche del sé.',
    archi: [
      ['numeri-e-geometria', 'usa_simbolo', 'La tetraktys e il numero come principio'],
      ['iniziazione', 'pratica', 'La divisione fra akousmatikoi e mathematikoi'],
      ['vie-contemplative', 'pratica', 'Silenzio dei novizi, esame di coscienza serale, regola alimentare'],
      ['esoterico-essoterico', 'elabora', 'La distinzione essoterico/esoterico prima che le parole esistano'],
      ['neoplatonismo', 'influenza', 'Il numero e l’armonia rientrano nella sintesi neoplatonica'],
      ['esoterismo-e-musica', 'influenza', 'L’armonia delle sfere fonda il rapporto musica-cosmo'],
    ],
    fonti: ['Burkert, Antichi culti misterici'],
  },
  {
    id: 'ermetismo',
    titolo: 'Ermetismo',
    tipo: 'corrente',
    parte: 2,
    peso: 5,
    periodo: [100, OGGI],
    luoghi: ['alessandria', 'firenze'],
    alias: ['tradizione ermetica', 'hermetica'],
    sommario:
      'La corrente riferita a Ermete Trismegisto: i trattati filosofici alessandrini, la letteratura tecnica, le due riscoperte — quella entusiasta del 1463 e quella demolitrice del 1614.',
    archi: [
      ['neoplatonismo', 'contemporaneo_di', 'Stesso ambiente tardoantico, temi affini'],
      ['corrispondenze', 'elabora', 'Ciò che è in basso è come ciò che è in alto'],
      ['macrocosmo-microcosmo', 'elabora'],
      ['astrologia', 'pratica', 'L’ermetismo tecnico: astrologia, alchimia, talismani'],
      ['talismani', 'pratica'],
      ['alchimia', 'influenza', 'La Tavola di Smeraldo diventa la sintesi proverbiale dell’opera'],
      ['magia-rinascimentale', 'influenza', 'Via Ficino, dal 1463'],
    ],
    fonti: ['Copenhaver, Hermetica', 'Fowden, The Egyptian Hermes', 'Yates, Giordano Bruno e la tradizione ermetica'],
  },
  {
    id: 'gnosticismo',
    titolo: 'Gnosticismo',
    tipo: 'corrente',
    parte: 2,
    peso: 5,
    periodo: [100, 400],
    luoghi: ['alessandria', 'roma'],
    alias: ['gnosi antica', 'gnostici'],
    sommario:
      'La galassia di movimenti dei primi secoli: un Dio estraneo al mondo, un demiurgo ignorante, una scintilla caduta nell’uomo e la salvezza per conoscenza. Un esoterismo del rifiuto del mondo, non della sua esaltazione.',
    archi: [
      ['gnosi', 'elabora', 'La salvezza non viene dalla fede né dalle opere ma dal risveglio'],
      ['ermetismo', 'contemporaneo_di', 'Stesso crogiolo alessandrino, valutazione opposta del cosmo'],
      ['serpente', 'usa_simbolo', 'Il rovesciamento ofita: il serpente come istruttore benefico contro il demiurgo'],
      ['catarismo', 'influenza', 'Eredità dualista per vie indirette e discusse'],
      ['teosofia-cristiana', 'influenza', 'Echi gnostici nella tensione tragica di Böhme'],
      ['manicheismo', 'influenza', 'Il dualismo radicale sistematizzato da Mani'],
    ],
    fonti: ['Jonas, Lo gnosticismo', 'Filoramo, L’attesa della fine'],
  },
  {
    id: 'manicheismo',
    titolo: 'Manicheismo',
    tipo: 'corrente',
    parte: 2,
    peso: 2,
    periodo: [240, 1400],
    sommario:
      'La religione universale fondata da Mani nel III secolo: dualismo radicale di luce e tenebra, scritture proprie, una diffusione dall’Impero romano fino alla Cina.',
    archi: [['luce-e-tenebra', 'usa_simbolo', 'Il conflitto cosmico dei due principi']],
    fonti: ['Jonas, Lo gnosticismo'],
  },
  {
    id: 'neoplatonismo',
    titolo: 'Neoplatonismo',
    tipo: 'corrente',
    parte: 2,
    peso: 5,
    periodo: [204, 529],
    luoghi: ['alessandria', 'atene', 'roma'],
    alias: ['scuola neoplatonica'],
    sommario:
      'Da Plotino a Proclo: l’emanazione dall’Uno e il ritorno a esso. Non un esoterismo in senso stretto, ma l’ossatura metafisica di quasi tutto l’esoterismo occidentale successivo.',
    archi: [
      ['emanazione', 'elabora', 'Prohodos ed epistrophē: uscita e ritorno'],
      ['gnosticismo', 'si_oppone_a', 'Plotino scrive contro gli gnostici: il cosmo non è una prigione'],
      ['teurgia', 'pratica', 'Da Giamblico in poi: il rito come via di ascesa'],
      ['luce-e-tenebra', 'usa_simbolo', 'L’emanazione pensata come diffusione luminosa'],
      ['cabala', 'influenza', 'L’architettura emanativa arriva alla cabala per mediazioni medievali'],
    ],
    fonti: ['Plotino, Enneadi', 'Faivre, Accès de l’ésotérisme occidental'],
  },
  {
    id: 'magia-medievale',
    titolo: 'Magia medievale',
    tipo: 'corrente',
    parte: 2,
    peso: 3,
    periodo: [1100, 1500],
    luoghi: ['parigi'],
    alias: ['negromanzia clericale', 'magia astrale medievale'],
    sommario:
      'Il ritorno dell’astrologia e della magia astrale attraverso le traduzioni dall’arabo, la negromanzia dei chierici alfabetizzati, la condanna del 1277: i novecento anni che rendono possibile il Rinascimento.',
    archi: [
      ['ermetismo', 'deriva_da', 'La letteratura tecnica araba attribuita a Ermete'],
      ['astrologia', 'pratica', 'Adottata dalla medicina universitaria come strumento diagnostico'],
      ['talismani', 'pratica', 'Il Picatrix e la magia delle immagini astrali'],
      ['magia-cerimoniale', 'pratica', 'Ars notoria e manuali di evocazione fra i chierici'],
      ['magia-rinascimentale', 'influenza', 'Fonti dirette di Ficino e Agrippa'],
    ],
    fonti: ['Goodrick-Clarke, The Western Esoteric Traditions'],
  },
  {
    id: 'catarismo',
    titolo: 'Catarismo',
    tipo: 'corrente',
    parte: 2,
    peso: 2,
    periodo: [1150, 1330],
    sommario:
      'Il dualismo nell’Occidente latino, annientato dalla crociata: la sua eredità più duratura è di secondo grado — il mito dei perseguitati depositari di un sapere segreto.',
    archi: [
      ['leggenda-templare', 'influenza', 'Il modello dei perseguitati sapienti passa poi ai templari'],
    ],
  },
  {
    id: 'cabala',
    titolo: 'Cabala ebraica',
    tipo: 'corrente',
    parte: 2,
    peso: 5,
    periodo: [1170, OGGI],
    luoghi: ['provenza-e-catalogna', 'safed'],
    alias: ['qabbalah', 'kabbalah', 'mistica ebraica'],
    sommario:
      '«Ricezione»: la mistica speculativa ebraica emersa fra Provenza e Catalogna nel XII-XIII secolo, con radici nella Merkavah e nel Sefer Yetzirah. Le dieci sefirot, il potere creatore della lettera, l’esegesi infinita.',
    archi: [
      ['emanazione', 'elabora', 'Le sefirot come processo di emanazione divina'],
      ['albero-sefirotico', 'usa_simbolo', 'Il diagramma delle dieci sefirot e dei ventidue sentieri'],
      ['numeri-e-geometria', 'usa_simbolo', 'Ghematria: il valore numerico delle lettere'],
      ['velo-e-occultamento', 'elabora', 'PaRDeS: i quattro livelli dell’esegesi'],
      ['vie-contemplative', 'pratica', 'La linea estatica di Abulafia: permutazioni, respirazione, nomi divini'],
    ],
    fonti: ['Scholem, Le grandi correnti della mistica ebraica', 'Idel, Cabbalà. Nuove prospettive'],
  },
  {
    id: 'cabala-cristiana',
    titolo: 'Cabala cristiana',
    tipo: 'corrente',
    parte: 2,
    peso: 4,
    periodo: [1486, 1700],
    luoghi: ['firenze'],
    alias: ['christian kabbalah'],
    sommario:
      'La ripresa rinascimentale della cabala da parte di dotti cristiani, con finalità apologetiche e magiche: da Pico e Reuchlin alla Kabbala Denudata, il canale attraverso cui le sefirot entrano nell’esoterismo europeo.',
    archi: [
      ['cabala', 'deriva_da', 'Ripresa cristiana della tradizione ebraica, con torsioni apologetiche'],
      ['prisca-theologia', 'elabora', 'La cabala arruolata fra le testimonianze della sapienza originaria'],
      ['occultismo', 'influenza', 'Via Lévi, fino alla kabbalah occultistica priva di ebraico'],
    ],
    fonti: ['Scholem, La Cabala', 'Yates, Giordano Bruno e la tradizione ermetica'],
  },
  {
    id: 'cabala-luriana',
    titolo: 'Cabala luriana',
    tipo: 'corrente',
    parte: 2,
    peso: 4,
    periodo: [1550, OGGI],
    luoghi: ['safed'],
    alias: ['scuola di Safed', 'luria'],
    sommario:
      'La rifondazione di Isaac Luria a Safed: tzimtzum (contrazione), shevirat ha-kelim (rottura dei vasi), tikkun (riparazione affidata all’agire umano). Una delle cosmogonie più originali mai concepite.',
    archi: [
      ['cabala', 'deriva_da', 'Rifondazione cinquecentesca della tradizione ricevuta'],
      ['emanazione', 'elabora', 'Lo tzimtzum: l’Infinito si ritira per fare spazio al mondo'],
      ['reintegrazione', 'elabora', 'Il tikkun come compito cosmico dell’uomo'],
    ],
    fonti: ['Scholem, Le grandi correnti della mistica ebraica'],
  },
  {
    id: 'alchimia',
    titolo: 'Alchimia',
    tipo: 'corrente',
    parte: 2,
    peso: 5,
    periodo: [100, 1750],
    luoghi: ['alessandria'],
    alias: ['arte regia', 'ars magna'],
    sommario:
      'Tre fasi — greco-egizia, araba, latina — di una disciplina che unisce operazioni di laboratorio, teoria dei principi e simbolismo trasformativo. Chimica, truffa e allegoria coesistono, spesso nello stesso autore.',
    archi: [
      ['trasmutazione', 'elabora', 'Il piombo in oro: preteso alla lettera, smentito dalla chimica del nucleo'],
      ['opera-alchemica', 'pratica', 'Nigredo, albedo, citrinitas, rubedo'],
      ['ouroboros', 'usa_simbolo', 'Fra le più antiche immagini alchemiche documentate'],
      ['coniunctio', 'usa_simbolo', 'Lo schema nuziale: Sole e Luna, zolfo e mercurio'],
      ['pietra-filosofale', 'usa_simbolo'],
      ['uccelli-alchemici', 'usa_simbolo', 'Corvo, cigno, fenice: il progresso dell’opera senza nominare le sostanze'],
      ['uovo', 'usa_simbolo', 'Il vaso sigillato come uovo filosofico'],
      ['paracelsismo', 'influenza', 'Paracelso sposta l’obiettivo: non fare oro ma fare medicine'],
    ],
    fonti: ['Principe, The Secrets of Alchemy', 'Eliade, Arti del metallo e alchimia'],
  },
  {
    id: 'paracelsismo',
    titolo: 'Paracelsismo',
    tipo: 'corrente',
    parte: 2,
    peso: 3,
    periodo: [1530, 1700],
    alias: ['iatrochimica', 'spagiria'],
    sommario:
      'La corrente medico-filosofica derivata da Paracelso: i tria prima (zolfo, mercurio, sale), la dottrina delle segnature, la preparazione chimica dei rimedi. Una linea porta alla farmacologia moderna.',
    archi: [
      ['alchimia', 'deriva_da', 'L’alchimia orientata alla medicina'],
      ['segnature', 'elabora', 'Ogni cosa porta impresso nella forma il segno della propria virtù'],
      ['teosofia-cristiana', 'influenza', 'Böhme legge i paracelsisti'],
    ],
    fonti: ['Principe, The Secrets of Alchemy'],
  },
  {
    id: 'magia-rinascimentale',
    titolo: 'Magia rinascimentale',
    tipo: 'corrente',
    parte: 2,
    peso: 5,
    periodo: [1460, 1620],
    luoghi: ['firenze', 'londra'],
    alias: ['magia naturalis', 'magia dotta'],
    sommario:
      'Il momento senza precedenti in cui la magia diventa quasi rispettabile: Ficino e la magia astrale medica, Pico e la cabala, Agrippa e i tre mondi, Bruno e la memoria, Dee e gli angeli.',
    archi: [
      ['neoplatonismo', 'deriva_da', 'Il cosmo animato dell’anima mundi'],
      ['ermetismo', 'deriva_da', 'La riscoperta ficiniana del Corpus Hermeticum'],
      ['magia-medievale', 'deriva_da', 'Il Picatrix come fonte diretta del De vita III'],
      ['prisca-theologia', 'elabora'],
      ['corrispondenze', 'elabora', 'La corrispondenza come fisica del cosmo qualitativo'],
      ['magia-naturale', 'pratica'],
      ['magia-cerimoniale', 'pratica', 'Il terzo libro di Agrippa: nomi divini, angeli, cerimoniale'],
      ['talismani', 'pratica'],
      ['arte-della-memoria', 'pratica', 'Bruno: le immagini mnemoniche ordinano l’anima secondo il cosmo'],
    ],
    fonti: ['Yates, Giordano Bruno e la tradizione ermetica', 'Walker, Spiritual and Demonic Magic', 'Culianu, Eros e magia nel Rinascimento'],
  },
  {
    id: 'templari',
    titolo: 'Templari',
    tipo: 'corrente',
    parte: 2,
    peso: 3,
    periodo: [1119, 1314],
    alias: ['Ordine del Tempio', 'cavalieri templari'],
    sommario:
      'L’ordine monastico-cavalleresco storico, sciolto con il processo del 1307-1314. Nessuna fonte medievale gli attribuisce un sapere segreto: la leggenda è una costruzione settecentesca degli alti gradi massonici.',
    archi: [
      ['leggenda-templare', 'influenza', 'Il processo e il rogo forniscono la materia prima del mito'],
      ['alti-gradi', 'attribuzione_infondata', 'La discendenza templare rivendicata dalla Stretta Osservanza (1751) è un’invenzione settecentesca: nessuna catena documentata collega l’ordine sciolto nel 1314 alla massoneria.'],
      ['rosacrocianesimo', 'attribuzione_infondata', 'L’accostamento templari-rosacroce è una saldatura romantica posteriore: i manifesti del 1614 non menzionano i templari.'],
    ],
    fonti: ['Partner, The Murdered Magicians'],
  },
  {
    id: 'rosacrocianesimo',
    titolo: 'Rosacroce',
    tipo: 'corrente',
    parte: 2,
    peso: 4,
    periodo: [1614, OGGI],
    alias: ['rosacrocianesimo', 'fraternità rosacroce'],
    sommario:
      'La fraternità annunciata dai manifesti del 1614-1616, di cui non esiste alcuna attestazione anteriore: il caso di scuola dell’invenzione di tradizione — un mito fondativo che, non trovando la realtà, la genera.',
    archi: [
      ['invenzione-di-tradizione', 'elabora', 'Tutte le organizzazioni rosacrociane documentate sono successive ai manifesti'],
      ['rosa-e-croce', 'usa_simbolo'],
      ['alchimia', 'deriva_da', 'L’immaginario alchemico e nuziale delle Nozze chimiche'],
      ['alti-gradi', 'influenza', 'I gradi Rose-Croix del Settecento massonico: influenza letteraria reale'],
      ['massoneria', 'attribuzione_infondata', 'La continuità fra la fraternità del 1614 (mai esistita come organizzazione) e la massoneria è rivendicazione settecentesca senza base documentaria.'],
    ],
    fonti: ['Yates, L’illuminismo dei Rosacroce'],
  },
  {
    id: 'teosofia-cristiana',
    titolo: 'Teosofia cristiana',
    tipo: 'corrente',
    parte: 2,
    peso: 3,
    periodo: [1600, 1800],
    alias: ['teosofia boehmiana', 'pietismo esoterico'],
    sommario:
      'La corrente luterana che da Böhme a Oetinger pensa Dio come processo attraversato da una tensione tragica: una delle sorgenti sotterranee dell’idealismo tedesco e del romanticismo.',
    archi: [
      ['emanazione', 'elabora', 'L’Ungrund e la manifestazione come processo teogonico'],
      ['martinismo', 'influenza', 'Saint-Martin traduce Böhme'],
      ['esoterismo-e-letteratura', 'influenza', 'Schelling e Hegel leggono Böhme; il romanticismo ne assorbe la natura vivente'],
    ],
    fonti: ['Faivre, Accès de l’ésotérisme occidental'],
  },
  {
    id: 'massoneria',
    titolo: 'Massoneria',
    tipo: 'corrente',
    parte: 2,
    peso: 4,
    periodo: [1717, OGGI],
    luoghi: ['londra'],
    alias: ['libera muratoria', 'framassoneria'],
    sommario:
      'Nata nel 1717 come società di sociabilità civile e perfezionamento morale, adotta il vocabolario del cantiere come linguaggio simbolico. Non discende dai costruttori medievali se non per adozione simbolica.',
    archi: [
      ['iniziazione', 'pratica', 'Camerino di riflessione, prove, morte simbolica del grado di maestro'],
      ['sistema-dei-gradi', 'pratica', 'Tre gradi simbolici, poi la proliferazione degli alti gradi'],
      ['casa-e-tempio', 'usa_simbolo', 'Pietra grezza e levigata, squadra e compasso, il tempio da costruire'],
      ['invenzione-di-tradizione', 'elabora', 'L’origine egizio-templare è costruita a posteriori'],
      ['esoterismo-e-politica', 'influenza', 'Tolleranza, cosmopolitismo, ideali costituzionali fra Sette e Ottocento'],
    ],
    fonti: ['Goodrick-Clarke, The Western Esoteric Traditions'],
  },
  {
    id: 'alti-gradi',
    titolo: 'Alti gradi massonici',
    tipo: 'corrente',
    parte: 2,
    peso: 3,
    periodo: [1740, OGGI],
    alias: ['Rito Scozzese', 'Stretta Osservanza'],
    sommario:
      'La proliferazione sette-ottocentesca di gradi cavallereschi, templari, alchemici e cabalistici innestati sul tronco massonico: il laboratorio in cui si fabbricano le genealogie leggendarie.',
    archi: [
      ['massoneria', 'deriva_da', 'Innesto sul tronco delle prime tre gradazioni'],
      ['leggenda-templare', 'elabora', 'La Stretta Osservanza e la discendenza templare rivendicata'],
      ['cabala-cristiana', 'deriva_da', 'Materiali cabalistici nei gradi superiori'],
    ],
    fonti: ['Goodrick-Clarke, The Western Esoteric Traditions'],
  },
  {
    id: 'martinismo',
    titolo: 'Martinismo',
    tipo: 'corrente',
    parte: 2,
    peso: 3,
    periodo: [1754, OGGI],
    luoghi: ['parigi'],
    alias: ['Élus Coëns', 'martinisti'],
    sommario:
      'Da Martinez de Pasqually a Saint-Martin: la reintegrazione dell’uomo nel suo stato primordiale, prima per teurgia cerimoniale, poi per via interiore — la «via del cuore» del Filosofo Incognito.',
    archi: [
      ['teurgia', 'pratica', 'Le operazioni degli Élus Coëns'],
      ['reintegrazione', 'elabora', 'Il concetto centrale della corrente'],
      ['massoneria', 'deriva_da', 'Nasce nell’ambiente degli alti gradi'],
    ],
    fonti: ['Faivre, Accès de l’ésotérisme occidental'],
  },
  {
    id: 'mesmerismo',
    titolo: 'Mesmerismo',
    tipo: 'corrente',
    parte: 2,
    peso: 3,
    periodo: [1774, 1850],
    luoghi: ['parigi'],
    alias: ['magnetismo animale'],
    sommario:
      'Il fluido universale di Mesmer e il sonnambulismo magnetico di Puységur: la commissione reale del 1784 vi individua, senza saperlo, la suggestione. Da questa radice nascono l’ipnosi clinica e, per altra via, l’idea moderna di inconscio.',
    archi: [
      ['spiritismo', 'influenza', 'Il sonnambulismo prepara la figura del medium'],
      ['sogni', 'influenza', 'Dalla trance magnetica alla scoperta dell’inconscio'],
    ],
    fonti: ['Godwin, The Theosophical Enlightenment'],
  },
  {
    id: 'spiritismo',
    titolo: 'Spiritismo',
    tipo: 'corrente',
    parte: 2,
    peso: 4,
    periodo: [1848, OGGI],
    luoghi: ['new-york', 'parigi'],
    alias: ['spiritualismo', 'sedute spiritiche'],
    sommario:
      'Dai colpi codificati di Hydesville alla sistemazione dottrinale di Kardec: la comunicazione con i defunti come fenomeno di massa, prima tribuna pubblica femminile e terreno delle prime indagini organizzate sul paranormale.',
    archi: [
      ['mesmerismo', 'deriva_da', 'La trance medianica discende dal sonnambulismo magnetico'],
      ['teosofia', 'influenza', 'Blavatsky esce dall’ambiente spiritista superandolo'],
      ['donne-ed-esoterismo', 'elabora', 'La seduta come unica tribuna pubblica disponibile alle donne'],
    ],
    fonti: ['Godwin, The Theosophical Enlightenment'],
  },
  {
    id: 'occultismo',
    titolo: 'Occultismo',
    tipo: 'corrente',
    parte: 2,
    peso: 4,
    periodo: [1854, 1920],
    luoghi: ['parigi'],
    alias: ['occultismo francese'],
    sommario:
      'La ricostruzione moderna, sistematica e divulgativa delle dottrine esoteriche, fondata da Éliphas Lévi: magia cerimoniale, cabala, alchimia e tarocchi unificati in un solo sistema. Ogni occultismo è esoterismo; non viceversa.',
    archi: [
      ['cabala', 'deriva_da', 'La kabbalah occultistica: terza cosa rispetto a qabbalah e cabala cristiana'],
      ['tarocchi', 'elabora', 'La corrispondenza arcani-lettere ebraiche stabilita da Lévi'],
      ['magia-cerimoniale', 'pratica'],
      ['golden-dawn', 'influenza', 'Il corpus di corrispondenze passa a Londra'],
    ],
    fonti: ['Godwin, The Theosophical Enlightenment'],
  },
  {
    id: 'teosofia',
    titolo: 'Teosofia (Società Teosofica)',
    tipo: 'corrente',
    parte: 2,
    peso: 5,
    periodo: [1875, OGGI],
    luoghi: ['new-york', 'londra'],
    alias: ['Società Teosofica', 'teosofia moderna'],
    sommario:
      'La sintesi di dimensioni cosmiche fondata da Blavatsky e Olcott nel 1875: cicli, Maestri, evoluzione spirituale. Porta karma, reincarnazione e chakra nel lessico comune e crea il modello organizzativo copiato da tutte le correnti successive.',
    archi: [
      ['spiritismo', 'deriva_da', 'Ne condivide l’ambiente d’origine, rifiutandone la pratica medianica'],
      ['concordanza-delle-tradizioni', 'elabora', 'Tutte le religioni come espressioni di un’unica sapienza'],
      ['corpo-sottile', 'elabora', 'L’immagine corrente dei sette chakra colorati è in larga parte costruzione teosofica'],
      ['antroposofia', 'influenza', 'Steiner se ne distacca nel 1912-13'],
      ['new-age', 'influenza', 'L’espressione «New Age» è di ascendenza teosofica'],
      ['esoterismo-e-arte', 'influenza', 'Kandinskij, Mondrian, af Klint: l’astrazione nasce anche da premesse teosofiche'],
    ],
    fonti: ['Godwin, The Theosophical Enlightenment', 'Goodrick-Clarke, The Western Esoteric Traditions'],
  },
  {
    id: 'antroposofia',
    titolo: 'Antroposofia',
    tipo: 'corrente',
    parte: 2,
    peso: 3,
    periodo: [1912, OGGI],
    alias: ['Società Antroposofica'],
    sommario:
      'Il movimento fondato da Rudolf Steiner dopo il distacco dalla Teosofia: una «scienza dello spirito» con applicazioni pratiche di lunga durata — pedagogia Waldorf, agricoltura biodinamica, medicina antroposofica.',
    archi: [['teosofia', 'deriva_da', 'Distacco del 1912-13 sulla direzione del movimento']],
    fonti: ['Goodrick-Clarke, The Western Esoteric Traditions'],
  },
  {
    id: 'golden-dawn',
    titolo: 'Golden Dawn',
    tipo: 'corrente',
    parte: 2,
    peso: 4,
    periodo: [1888, OGGI],
    luoghi: ['londra'],
    alias: ['Hermetic Order of the Golden Dawn', 'Alba Dorata'],
    sommario:
      'L’ordine magico londinese fondato nel 1888: una scala di gradi calcata sull’albero sefirotico e un corpus di corrispondenze che integra cabala, astrologia, tarocchi, enochiano e alchimia. La base tecnica della magia occidentale successiva.',
    archi: [
      ['occultismo', 'deriva_da', 'Sistematizza il materiale di Lévi e dell’occultismo francese'],
      ['albero-sefirotico', 'usa_simbolo', 'La scala dei gradi ricalcata sulle sefirot'],
      ['magia-cerimoniale', 'pratica'],
      ['vie-contemplative', 'pratica', 'Visualizzazione strutturata e scrying'],
      ['thelema', 'influenza', 'Crowley ne esce e fonda il proprio sistema'],
      ['wicca', 'influenza', 'Gardner attinge ai suoi materiali rituali'],
    ],
    fonti: ['Owen, The Place of Enchantment'],
  },
  {
    id: 'thelema',
    titolo: 'Thelema',
    tipo: 'corrente',
    parte: 2,
    peso: 3,
    periodo: [1904, OGGI],
    luoghi: ['il-cairo'],
    sommario:
      'Il sistema fondato da Crowley sul Liber AL vel Legis (1904): ciascuno deve compiere la propria Volontà vera — vocazione essenziale, non capriccio — con un’esigenza dichiarata di verifica sperimentale della pratica.',
    archi: [
      ['golden-dawn', 'deriva_da', 'Crowley ne fu iniziato e ne portò con sé il sistema'],
      ['magia-cerimoniale', 'pratica'],
      ['magia-del-caos', 'influenza', 'L’ambiente post-crowleyano è la matrice della corrente'],
    ],
    fonti: ['Owen, The Place of Enchantment'],
  },
  {
    id: 'tradizionalismo',
    titolo: 'Tradizionalismo',
    tipo: 'corrente',
    parte: 2,
    peso: 4,
    periodo: [1921, OGGI],
    luoghi: ['il-cairo'],
    alias: ['scuola tradizionale', 'perennialismo'],
    sommario:
      'Guénon, Coomaraswamy, Schuon, e con accenti propri Evola: la Tradizione primordiale unica, la modernità come decadenza. Non una teoria storiografica ma una dottrina metafisica: va conosciuta come oggetto di studio, non usata come metodo.',
    archi: [
      ['concordanza-delle-tradizioni', 'elabora', 'L’unità trascendente delle religioni come postulato metafisico'],
      ['catena-iniziatica', 'elabora', 'L’affiliazione regolare come criterio di validità'],
      ['occultismo', 'si_oppone_a', 'La rottura di Guénon con l’ambiente occultista francese'],
      ['spiritismo', 'si_oppone_a', 'L’Erreur spirite: condanna radicale della pratica medianica'],
      ['esoterismo-e-politica', 'influenza', 'L’uso militante di Evola nella destra radicale del dopoguerra'],
    ],
    fonti: ['Sedgwick, Against the Modern World'],
  },
  {
    id: 'wicca',
    titolo: 'Wicca',
    tipo: 'corrente',
    parte: 2,
    peso: 4,
    periodo: [1954, OGGI],
    luoghi: ['londra'],
    alias: ['stregoneria moderna', 'neopaganesimo'],
    sommario:
      'La stregoneria moderna resa pubblica da Gardner nel 1954: presentata come sopravvivenza di un culto antico, è una composizione novecentesca — il che non toglie nulla alla realtà del fenomeno e alla sua fecondità religiosa.',
    archi: [
      ['golden-dawn', 'deriva_da', 'Materiali rituali giunti via Crowley e la massoneria'],
      ['invenzione-di-tradizione', 'elabora', 'La «sopravvivenza» del culto della fertilità (tesi Murray) è infondata'],
      ['morte-e-rinascita', 'usa_simbolo', 'La ruota dell’anno e il ciclo stagionale'],
      ['donne-ed-esoterismo', 'elabora', 'Con Starhawk: teologia della Dea e femminismo'],
    ],
    fonti: ['Hutton, The Triumph of the Moon'],
  },
  {
    id: 'new-age',
    titolo: 'New Age',
    tipo: 'corrente',
    parte: 2,
    peso: 4,
    periodo: [1970, OGGI],
    sommario:
      'Il vasto movimento diffuso dagli anni Settanta: attesa di un mutamento di coscienza, sincretismo, autoguarigione. Nessuna dottrina né organizzazione: il passaggio dalla logica dell’iniziazione a quella del consumo.',
    archi: [
      ['teosofia', 'deriva_da', 'L’attesa dell’era nuova è di ascendenza teosofica'],
      ['concordanza-delle-tradizioni', 'elabora', '«Un solo messaggio» dietro tutte le tradizioni'],
      ['catena-iniziatica', 'si_oppone_a', 'Dal maestro e la soglia all’autoapprendimento componibile'],
    ],
    fonti: ['Hanegraaff, New Age Religion and Western Culture'],
  },
  {
    id: 'magia-del-caos',
    titolo: 'Magia del caos',
    tipo: 'corrente',
    parte: 2,
    peso: 2,
    periodo: [1975, OGGI],
    luoghi: ['londra'],
    alias: ['chaos magick'],
    sommario:
      'La corrente inglese che riduce l’apparato tradizionale a metodo minimale: i sistemi simbolici come strumenti intercambiabili, la credenza stessa come tecnica da assumere e deporre. L’esoterismo dell’epoca postmoderna.',
    archi: [
      ['thelema', 'deriva_da', 'Dalle intuizioni di Spare, nell’ambiente post-crowleyano'],
      ['teoria-del-simbolo', 'elabora', 'Il simbolo ridotto a strumento di efficacia dichiarata'],
    ],
  },
  {
    id: 'quarta-via',
    titolo: 'Quarta Via',
    tipo: 'corrente',
    parte: 2,
    peso: 2,
    periodo: [1912, OGGI],
    alias: ['Gurdjieff', 'il Lavoro'],
    sommario:
      'Il sistema di Gurdjieff: l’uomo ordinario vive in stato di sonno e automatismo, e la sveglia richiede un lavoro su di sé condotto in gruppo e sotto condizioni deliberatamente scomode.',
    archi: [
      ['vie-contemplative', 'pratica', 'Il «ricordo di sé» come esame continuo'],
      ['dinamiche-settarie', 'elabora', 'La linea sottile fra pedagogia esigente e controllo'],
    ],
  },
  {
    id: 'sufismo',
    titolo: 'Sufismo',
    tipo: 'corrente',
    parte: 2,
    peso: 2,
    periodo: [800, OGGI],
    alias: ['tasawwuf', 'mistica islamica'],
    sommario:
      'La dimensione interiore dell’Islam, con la distinzione fra zahir (esteriore) e batin (interiore) e le catene iniziatiche delle confraternite. Qui solo come termine di confronto: ogni comparazione richiede il suo contesto.',
    archi: [
      ['esoterico-essoterico', 'elabora', 'Zahir e batin: la coppia esteriore/interiore in contesto islamico'],
      ['catena-iniziatica', 'elabora', 'La silsila delle confraternite'],
      ['vie-contemplative', 'pratica', 'Il dhikr: la ripetizione del nome'],
    ],
    fonti: ['Corbin, L’immaginazione creatrice'],
  },
  {
    id: 'tantra',
    titolo: 'Tantra',
    tipo: 'corrente',
    parte: 2,
    peso: 1,
    periodo: [500, OGGI],
    sommario:
      'Le tradizioni indiane e tibetane del corpo sottile e della trasformazione rituale. Qui solo come termine di confronto: molte «corrispondenze» con l’Occidente sono state costruite dalla traduzione ottocentesca.',
    archi: [
      ['corpo-sottile', 'elabora', 'Chakra e nadi nei sistemi originari, più vari dell’immagine occidentale'],
      ['serpente', 'usa_simbolo', 'La kundalini arrotolata alla base della colonna'],
    ],
  },
  {
    id: 'alchimia-taoista',
    titolo: 'Alchimia interiore taoista',
    tipo: 'corrente',
    parte: 2,
    peso: 1,
    periodo: [700, OGGI],
    alias: ['neidan'],
    sommario:
      'Il neidan cinese: il lessico del laboratorio usato per descrivere trasformazioni interiori. Analogia strutturale con l’alchimia occidentale, senza contatto storico documentato per le fasi formative.',
    archi: [
      ['trasmutazione', 'elabora', 'Trasformazione dell’operatore con il lessico della fornace'],
      ['alchimia', 'contemporaneo_di', 'Analogia strutturale, non filiazione documentata'],
    ],
  },
];
